### ISSUE TITLE
It the demo working?

### ISSUE THREAD

**Issue by Ensanho** [danielstorey/WebAudioTrack#1]
hello, i am trying to record sound in my web app with ios safari. I was used iPad to your demo. it is nothing happen. Is the demo work? Or just my issue?

**Comment by Jfbl** [comment]
Hi Ensanho, I believe that WebRTC is only available on ios 11, so you must check your ipad version

**Comment by superplussed** [comment]
I'm on Safari 11.0.3 on MacOS, and it's not working there.

**Comment by superplussed** [comment]
Strange, I just went back to Safari to try it again and now it works.  Is there some inconsistancy?

**Comment by shayc** [comment]
I cant playback the recording on iOS 12 public beta, will digg in later
