### ISSUE TITLE
It doesnt work on Chrome on iphone/ipad

### ISSUE THREAD

**Issue by trungquangphan** [danielstorey/WebAudioTrack#2]
This lib is working very well on Safari (Mac, iOS).
However it can not capture the microphone on Chrome on ipad/iphone.
Hope you can fix this issue and thank for good lib

**Comment by danielstorey** [comment]
Thanks and I’m glad it’s working well in safari. Unfortunately chrome on IOS does not yet support getUserMedia. Support in Safari was only added fairly recently in v 11 so Chrome hasn’t quite caught up yet. Hopefully support will be added in an update soon.
